[build]
target = "src/arch/x86_64/x86_64-unknown-kernel.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-x86_64 -serial stdio -gdb tcp::1234 -no-shutdown -no-reboot -kernel"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
